/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScannersIndexRouteImport } from './routes/scanners.index'
import { Route as ScannersNewRouteImport } from './routes/scanners.new'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ScannersIdEditRouteImport } from './routes/scanners.$id.edit'

const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannersIndexRoute = ScannersIndexRouteImport.update({
  id: '/scanners/',
  path: '/scanners/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannersNewRoute = ScannersNewRouteImport.update({
  id: '/scanners/new',
  path: '/scanners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannersIdEditRoute = ScannersIdEditRouteImport.update({
  id: '/scanners/$id/edit',
  path: '/scanners/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/api/$': typeof ApiSplatRoute
  '/runs/$id': typeof RunsIdRoute
  '/scanners/new': typeof ScannersNewRoute
  '/scanners/': typeof ScannersIndexRoute
  '/scanners/$id/edit': typeof ScannersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/api/$': typeof ApiSplatRoute
  '/runs/$id': typeof RunsIdRoute
  '/scanners/new': typeof ScannersNewRoute
  '/scanners': typeof ScannersIndexRoute
  '/scanners/$id/edit': typeof ScannersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/api/$': typeof ApiSplatRoute
  '/runs/$id': typeof RunsIdRoute
  '/scanners/new': typeof ScannersNewRoute
  '/scanners/': typeof ScannersIndexRoute
  '/scanners/$id/edit': typeof ScannersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/api/$'
    | '/runs/$id'
    | '/scanners/new'
    | '/scanners/'
    | '/scanners/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/api/$'
    | '/runs/$id'
    | '/scanners/new'
    | '/scanners'
    | '/scanners/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/api/$'
    | '/runs/$id'
    | '/scanners/new'
    | '/scanners/'
    | '/scanners/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  ApiSplatRoute: typeof ApiSplatRoute
  RunsIdRoute: typeof RunsIdRoute
  ScannersNewRoute: typeof ScannersNewRoute
  ScannersIndexRoute: typeof ScannersIndexRoute
  ScannersIdEditRoute: typeof ScannersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanners/': {
      id: '/scanners/'
      path: '/scanners'
      fullPath: '/scanners/'
      preLoaderRoute: typeof ScannersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanners/new': {
      id: '/scanners/new'
      path: '/scanners/new'
      fullPath: '/scanners/new'
      preLoaderRoute: typeof ScannersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanners/$id/edit': {
      id: '/scanners/$id/edit'
      path: '/scanners/$id/edit'
      fullPath: '/scanners/$id/edit'
      preLoaderRoute: typeof ScannersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  ApiSplatRoute: ApiSplatRoute,
  RunsIdRoute: RunsIdRoute,
  ScannersNewRoute: ScannersNewRoute,
  ScannersIndexRoute: ScannersIndexRoute,
  ScannersIdEditRoute: ScannersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
